### ISSUE TITLE
Build issues on Ubuntu/Debian

### ISSUE THREAD

**Issue by UbhaSecurity** [pothosware/SoapyHackRF#1]
ulf@hack:~/src$ cd SoapyHackRF/
ulf@hack:~/src/SoapyHackRF$ cd build/
ulf@hack:~/src/SoapyHackRF/build$ cmake ../
CMake Warning at CMakeLists.txt:14 (find_package):
  By not providing "FindLibHackRF.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibHackRF", but CMake did not find one.

  Could not find a package configuration file provided by "LibHackRF" with
  any of the following names:

    LibHackRFConfig.cmake
    libhackrf-config.cmake

  Add the installation prefix of "LibHackRF" to CMAKE_PREFIX_PATH or set
  "LibHackRF_DIR" to a directory containing one of the above files.  If
  "LibHackRF" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at CMakeLists.txt:17 (message):
  HackRF development files not found...

-- Configuring incomplete, errors occurred!
See also "/home/ulf/src/SoapyHackRF/build/CMakeFiles/CMakeOutput.log".

Locate points it to:

/usr/local/include/libhackrf
/usr/local/include/libhackrf/hackrf.h
/usr/local/lib/libhackrf.a
/usr/local/lib/libhackrf.so
/usr/local/lib/libhackrf.so.0
/usr/local/lib/libhackrf.so.0.3.0
/usr/local/lib/pkgconfig/libhackrf.pc

**Comment by jocover** [comment]
fixed cmake issues,you can try again

**Comment by UbhaSecurity** [comment]
ulf@hack:~/src/SoapyHackRF$ git pull
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 10), reused 9 (delta 5), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/jocover/SoapyHackRF
   dabc741..43656be  master     -> origin/master
Updating dabc741..43656be
Fast-forward
 CMakeLists.txt         |  6 +++++-
 HackRF_Registation.cpp | 37 +++++++++++++++++++++----------------
 HackRF_Settings.cpp    |  8 +++++---
 SoapyHackRF.hpp        |  1 +
 4 files changed, 32 insertions(+), 20 deletions(-)
ulf@hack:~/src/SoapyHackRF$ cd build/
ulf@hack:~/src/SoapyHackRF/build$ cmake ../
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found LIBHACKRF: /usr/local/lib/libhackrf.so  
-- LIBHACKRF_INCLUDE_DIRS - 
-- LIBHACKRF_LIBRARIES - /usr/local/lib/libhackrf.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ulf/src/SoapyHackRF/build
ulf@hack:~/src/SoapyHackRF/build$ make
Scanning dependencies of target HackRFSupport
[ 33%] Building CXX object CMakeFiles/HackRFSupport.dir/HackRF_Registation.cpp.o
[ 66%] Building CXX object CMakeFiles/HackRFSupport.dir/HackRF_Settings.cpp.o
[100%] Building CXX object CMakeFiles/HackRFSupport.dir/HackRF_Streaming.cpp.o
Linking CXX shared module libHackRFSupport.so
[100%] Built target HackRFSupport
ulf@hack:~/src/SoapyHackRF/build$ sudo make install
[sudo] password for ulf: 
[100%] Built target HackRFSupport
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/SoapySDR/modules/libHackRFSupport.so
-- Removed runtime path from "/usr/local/lib/SoapySDR/modules/libHackRFSupport.so"

Seems to build now.

Let's connect hackrf and see if it works :)

**Comment by UbhaSecurity** [comment]
ulf@hack:~/src/CubicSDR/build$ cd x64/
ulf@hack:~/src/CubicSDR/build/x64$ ./CubicSDR 
Loading:: configuration file '/home/ulf/.CubicSDR/config.xml'
Loaded PPM for device 'Generic RTL2832U OEM :: 00000001' at 0ppm
SoapySDR init..
	API Version: v0.3.0-g9671ca26
	ABI Version: v0.3-0
	Install root: /usr/local
	Module found: /usr/local/lib/SoapySDR/modules/libHackRFSupport.so
	Module found: /usr/local/lib/SoapySDR/modules/libhackrfSupport.so
	Module found: /usr/local/lib/SoapySDR/modules/librtlSupport.so
	Loading modules... done
	Available factories...hackrf, null, rtl
Found device 0
  driver = hackrf
  hackrf = 0
  label = HackRF HackRF One
Make device 0
Using HackRF One with firmware git-4e98bc6 
Error making device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB


SDR thread initializing..
Using device #0
SDR post-processing thread started..
Spectrum visual data thread started.
Spectrum visual data thread started.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
Aborted

I got the same with osmo block driver, so I'm guessing I have firmware issues or udev rules or some other issue.

**Comment by UbhaSecurity** [comment]
Nope.. Not firmware on the Hackrf..

ulf@hack:~/src/CubicSDR/build/x64$ ./CubicSDR 
Loading:: configuration file '/home/ulf/.CubicSDR/config.xml'
Loaded PPM for device 'Generic RTL2832U OEM :: 00000001' at 0ppm
SoapySDR init..
	API Version: v0.3.0-g9671ca26
	ABI Version: v0.3-0
	Install root: /usr/local
	Module found: /usr/local/lib/SoapySDR/modules/libHackRFSupport.so
	Module found: /usr/local/lib/SoapySDR/modules/libhackrfSupport.so
	Module found: /usr/local/lib/SoapySDR/modules/librtlSupport.so
	Loading modules... done
	Available factories...hackrf, null, rtl
Found device 0
  driver = hackrf
  hackrf = 0
  label = HackRF HackRF One
Make device 0
Using HackRF One with firmware 2015.07.2 
Error making device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB


SDR thread initializing..
Using device #0
SDR post-processing thread started..
Spectrum visual data thread started.
Spectrum visual data thread started.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
Aborted

Prob distro issue.. I try nail this myself.

**Comment by UbhaSecurity** [comment]
It works now!!!

I removed the osmo soapy lib.

Awesome.

**Comment by guruofquality** [comment]
Probably after a little more testing, I will make the SoapyOsmo RTL and hackrf support default to off, and make a note on the wiki about it (already did w/ the bladerf). That way, there wont be a collision. In the meantime, one can pass -DENABLE_HACKRF=OFF when configuring SoapyOsmo
