### ISSUE TITLE
Unclear copyright headers

### ISSUE THREAD

**Issue by andreasbombe** [pothosware/SoapyHackRF#12]
While trying to package this software for Debian, I was held back by the unclear copyright headers. Except for HackRF_Session.cpp, the copyright lines list a year but no copyright holder. The debian/copyright just quotes "jocover" as a copyright holder even though it is not found in the source files.

Judging from the git log, "jocover" seems to be basically correct, but I'd prefer explicit copyright lines that would make it clear that that is indeed the preferred way to be named as the copyright holder.

**Comment by guruofquality** [comment]
@jocover Can you modify the copyright lines to include your name, or something else of your choosing? Basically the source files and debian/copyright file should all match to the same copyright holder.

I could do it myself, but its probably better if the author makes the commit. Something like this for example:
```
  * The MIT License (MIT)
  *
- * Copyright (c) 2015
+ * Copyright (c) 2015 Wei Jiang
  * Permission is hereby granted, free of charge, to any person obtaining a copy
```

**Comment by guruofquality** [comment]
Done - https://github.com/pothosware/SoapyHackRF/commit/d8f36423f6704bd97ac3426dd2635cbcab6d1668
