### ISSUE TITLE
AMP slider always reset to 0 on CubicSDR

### ISSUE THREAD

**Issue by vsonnier** [pothosware/SoapyHackRF#18]
Reported initially as a CubicSDR issue : https://github.com/cjcliffe/CubicSDR/issues/602

I think the minus sign here in `getGain` for AMP is plainly wrong, and looks like a typo: 
https://github.com/pothosware/SoapyHackRF/blob/4667336afafd95380767b2817289de620d5ee634/HackRF_Settings.cpp#L423

Indeed the symetric `setGain` where the AMP gain is stored simply have:
https://github.com/pothosware/SoapyHackRF/blob/4667336afafd95380767b2817289de620d5ee634/HackRF_Settings.cpp#L360

I don't have a HackRF to confirm it, so I can't investigate further here.

**Comment by guruofquality** [comment]
I would say its a pretty old typo that even lasted through a refactor. The getters dont get tested as often as the setters. Anyway, I pushed a fix to master, Im positive that no one intended negative gain, and this way it now matches up with the setter. Thanks
