### ISSUE TITLE
Move SoapyHackRF pothosware organization

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyHackRF#2]
Hey @jocover SoapyHackRF looks good. I would like to make it official.

Rather than forking the repo, I would like to host this officially on the pothosware github organization along with SoapySDR and the other support modules. Would you mind transfering to my user account "guruofquality"?
* https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

After that I can move it to pothosware organization, give your account full access. Then its usuall project polishing stuff like wiki instructions, testing, version tags, debian packaging, building on windows.

Thanks,
-josh

**Comment by jocover** [comment]
OK

**Comment by guruofquality** [comment]
Done. Thanks!
