### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ryanvolz** [pothosware/SoapyHackRF#34]
I'm looking to build a SoapyHackRF package for conda-forge, and I see that it has been a little while since there was a release. Conda-forge policy is to only package based on tagged tarballs, so I will have to base the package on `soapy-hackrf-0.3.3` as of now. I can carry patches for the commits since then which look like useful bug fixes, and there aren't that many so it wouldn't be difficult, but it would certainly be cleaner to start from a fresh release. Any chance you could tag 0.4.0? No worries if not, but I figured it wouldn't hurt to ask. edit: Looks like 0.4.0 would be the next release according to the CMake.

**Comment by guruofquality** [comment]
Good idea https://github.com/pothosware/SoapyHackRF/releases/tag/soapy-hackrf-0.3.4
