### ISSUE TITLE
How to install SoapyHackRF into DietPi

### ISSUE THREAD

**Issue by ngmacha** [pothosware/SoapyHackRF#45]
I am running OpenWebRX on the DietPi based on Debian Bullseye (hardware is a PineA64 SBC), and would like to use the HackRF as an SDR. The OpenWebRX requirement for HackRF is SoapyHackRF, however I seem can't find how to install it - there's no package support for Debian. Please help, thanks alot!

**Comment by mossmann** [comment]
I think you should be able to `apt install soapysdr-module-hackrf` on Bullseye: https://packages.debian.org/en/bullseye/soapysdr-module-hackrf

**Comment by ngmacha** [comment]
@mossmann Thank you very much, that's what I needed!
