### ISSUE TITLE
Support transmit/receive switching

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyHackRF#7]
The goal of this issue is to ensure that both SoapySDR receive and transmit streams can be active at the same time. And that when the user sends TX samples, the receive stream, if active, will be switched off and the TX stream switched on. The end of burst flag or underflow in the TX thread will switch back the streams to RX active.

This may be a clumsy/slow way to switch, but I believe its the only way to implement this given the current libhackrf, and it will let users play around with modems that operate continuous receive and bursty transmit. Osmo block users will be able to instantiate both the source and sink for HackRF using the soapy support in GrOsmoSDR.

**Comment by jocover** [comment]
![work1](https://cloud.githubusercontent.com/assets/736509/10907353/453daf5a-8264-11e5-8744-abe2b89e4504.jpg)
tx/rx auto switching work fine on newest version

**Comment by guruofquality** [comment]
Very awesome, thanks for all the great progress!

**Comment by guruofquality** [comment]
@jocover I was thinking about the case of automatic switching where the user is continuously receiving with a thread and they have no control over stream activate/deactivate. In this case, we want to support switching automatically when there is transmit data.

I see that in acquireWriteBuffer(), the switching is automatic to enable transmit. But I am curious about the automatic disable of transmit as well.
```
	if(_current_mode!=TRANSCEIVER_MODE_TX) {
		int ret=this->activateStream(stream);
		if(ret<0) return ret;
	}
```

In acquireReadBuffer(), the function switches back to RX regardless if there is tx data. Maybe it should check the tx fifo first and wait for tx fifo completion. This is an example idea:
```
	if ( _current_mode!=TRANSCEIVER_MODE_RX ) {

               //----- added this code to wait for tx complete -----------//
               {
                 std::unique_lock<std::mutex> lock(_buf_mutex);
                 if (_tx_stream->buf_count != 0)
                 {
                         _buf_cond.wait_for(lock, std::chrono::microseconds(timeoutUs));
                         if (_tx_stream->buf_count != 0) return SOAPY_SDR_TIMEOUT;
                  }
                }

		int ret=this->activateStream(stream);
		if(ret<0) return ret;
	}
```

I'm still looking at the new code, sorry if I misunderstood something.

**Comment by jocover** [comment]
wait tx complete code in https://github.com/pothosware/SoapyHackRF/blob/master/HackRF_Streaming.cpp#L289

**Comment by guruofquality** [comment]
Thanks, now I see that code. I think this line briefly becomes a 100% CPU loop. A think a small sleep inside the loop would help:

```
while(hackrf_is_streaming(_dev)==HACKRF_TRUE)
{
std::chrono::sleep_for(std::chrono::milliseconds(10));
}
```

**Comment by jnunezortuno** [comment]
> ![work1](https://cloud.githubusercontent.com/assets/736509/10907353/453daf5a-8264-11e5-8744-abe2b89e4504.jpg)
> tx/rx auto switching work fine on newest version

Please, can you post the pothos file to test? I've copied the one in the image and doesn't works for me
